apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: serverless-sqs-lambda-other-${{values.name}}
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  path: ./terraform-sqs-lambda
  approvePlan: auto
  retryInterval: 10s
  interval: 2m
  destroyResourcesOnDeletion: true
  sourceRef:
    kind: GitRepository
    name: "serverless-sqs-lambda-other-${{values.name}}-git-repository"
    namespace: flux-system
  varsFrom:
    - kind: ConfigMap
      name: "serverless-sqs-lambda-other-${{values.name}}-tf-cm"
  runnerPodTemplate:
    spec:
      containers:
        - name: terraform
          image: ghcr.io/weaveworks/tf-runner:v0.15.2
          command:
            - /bin/sh
            - -c
          args:
            - |
              apt-get update && apt-get install -y python3 python3-pip
              terraform-runner
      envFrom:
        - secretRef:
            name: aws-credentials